version: '3.6'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nestjs_learn_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  graphql-engine:
    image: hasura/graphql-engine:v2.43.0
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://postgres:123456789@postgres:5432/nestjs_learn_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "oursupersecretsupersecurekey1234567890"}'
      HASURA_GRAPHQL_ADMIN_SECRET: '123456789'
      HASURA_GRAPHQL_ACTION_BASE_URL: "http://172.17.0.1:9090/actions"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/healthz']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:
